<?php

/**
 * @file
 * The Email Address Username module makes the user register with their email address.
 */

/**
 * Implementation of hook_form_alter to:
 * 1. Hide the username field,
 * 2. Add our custom submit function.
 *
 * @param $form
 * @param $form_state
 * @param int $form_id
 */
function email_address_username_form_alter(&$form, &$form_state, $form_id){
  if ($form['#form_id'] === 'user_register_form') {
    $form['account']['name'] = ''; // Removes the username field.
    // array_unshift is used to put the custom submit function to the front of the queue.
    array_unshift($form['#submit'], 'email_address_username_registration_submit');
  }
}

/**
 * Submit function to copy the email address into the now invisible username field..
 *
 * @param $form
 * @param array $form_state
 */
function email_address_username_registration_submit(&$form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
}